name: Git Server
version: "2.6"
slug: git_server
full_access: true
description: Private Git server with SSH for local development
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
init: false
host_network: true
privileged:
  - SYS_ADMIN
map:
  - share:rw
options:
  public_key: "ssh-rsa AAAA...your-key..."
schema:
  public_key: str
