name: Git Server
version: "1.0"
slug: git_server
description: Private Git server with SSH for local development and backup
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
init: false
host_network: true
privileged:
  - SYS_ADMIN
map:
  - share:rw
options: 
 key: ""
schema:
 key: str
